/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (BayesNet.as).
 */

package com.plummersmind.bayesexample.data {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class BayesNetBase implements IExternalizable {

        private var _name:String;
        private var _nodes:ListCollectionView;

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set nodes(value:ListCollectionView):void {
            _nodes = value;
        }
        public function get nodes():ListCollectionView {
            return _nodes;
        }

        public function readExternal(input:IDataInput):void {
            _name = input.readObject() as String;
            _nodes = input.readObject() as ListCollectionView;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject((_name is IPropertyHolder) ? IPropertyHolder(_name).object : _name);
            output.writeObject((_nodes is IPropertyHolder) ? IPropertyHolder(_nodes).object : _nodes);
        }
    }
}