/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CPTableEntry.as).
 */

package com.plummersmind.bayesexample.data {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class CPTableEntryBase implements IExternalizable {

        private var _parentState:String;
        private var _probabilities:ListCollectionView;

        public function set parentState(value:String):void {
            _parentState = value;
        }
        public function get parentState():String {
            return _parentState;
        }

        public function set probabilities(value:ListCollectionView):void {
            _probabilities = value;
        }
        public function get probabilities():ListCollectionView {
            return _probabilities;
        }

        public function readExternal(input:IDataInput):void {
            _parentState = input.readObject() as String;
            _probabilities = input.readObject() as ListCollectionView;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject((_parentState is IPropertyHolder) ? IPropertyHolder(_parentState).object : _parentState);
            output.writeObject((_probabilities is IPropertyHolder) ? IPropertyHolder(_probabilities).object : _probabilities);
        }
    }
}