/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.plummersmind.bayesexample.data {

    [Bindable]
    [RemoteClass(alias="com.plummersmind.bayesexample.data.NodeEquation")]
    public class NodeEquation extends NodeEquationBase 
	{
		public function NodeEquation(equation:String = null, numSamples:Number=0, 
									 includeUncertainty:Boolean=false, addExisting:Boolean=false)
		{
			this.equation = equation;
//			this.equationToTable_NumSamples = numSamples;
//			this.equationToTable_IncludeSamplingUncertainty = includeUncertainty;
//			this.equationToTable_addExisting = addExisting;
			
		}
    }
}