/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (NodeEquation.as).
 */

package com.plummersmind.bayesexample.data {

    import com.plummersmind.bayesexample.entities.AbstractEntity;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class NodeEquationBase extends AbstractEntity {

        private var _equation:String;

        public function set equation(value:String):void {
            _equation = value;
        }
        public function get equation():String {
            return _equation;
        }

        public override function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _equation = input.readObject() as String;
        }

        public override function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject((_equation is IPropertyHolder) ? IPropertyHolder(_equation).object : _equation);
        }
    }
}