/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.plummersmind.bayesexample.services {

    [Bindable]
    [RemoteClass(alias="com.plummersmind.bayesexample.services.BayesNetworkService")]
    public class BayesNetworkService extends BayesNetworkServiceBase {
    }
}