/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (BayesNetworkService.as).
 */

package com.plummersmind.bayesexample.services {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.tide.IPropertyHolder;

    [Bindable]
    public class BayesNetworkServiceBase implements IExternalizable, IBayesNetworkService {


        public function readExternal(input:IDataInput):void {
        }

        public function writeExternal(output:IDataOutput):void {
        }
    }
}