/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.plummersmind.bayesexample.services {

    [RemoteClass(alias="com.plummersmind.bayesexample.services.IBayesNetworkService")]
    public class IBayesNetworkService extends IBayesNetworkServiceBase {
    }
    
}
