/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.plummersmind.bayesexample.services {

    import com.plummersmind.bayesexample.data.BayesNet;

    public interface IBayesNetworkService {

        function get testBayesNetwork():BayesNet;
    }
}